// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF0FRAvZTI1yV-TNhhF9cCx37swU1YvU0',
    appId: '1:203559158951:web:579d00d6829fe8325d8782',
    messagingSenderId: '203559158951',
    projectId: 'gocoachapp-d882a',
    authDomain: 'gocoachapp-d882a.firebaseapp.com',
    storageBucket: 'gocoachapp-d882a.appspot.com',
    measurementId: 'G-PEQCMSRKXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqiLZ2Up9rHzsF61DRYSnAxUZ2WKMzsp8',
    appId: '1:203559158951:android:ff8d310c6459bb455d8782',
    messagingSenderId: '203559158951',
    projectId: 'gocoachapp-d882a',
    storageBucket: 'gocoachapp-d882a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPWdeoEPwQhZBbREjOshghEBKPzgX-4Z4',
    appId: '1:203559158951:ios:32b97d7fc3b7d24f5d8782',
    messagingSenderId: '203559158951',
    projectId: 'gocoachapp-d882a',
    storageBucket: 'gocoachapp-d882a.appspot.com',
    iosBundleId: 'com.example.adminPanelGocoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPWdeoEPwQhZBbREjOshghEBKPzgX-4Z4',
    appId: '1:203559158951:ios:32b97d7fc3b7d24f5d8782',
    messagingSenderId: '203559158951',
    projectId: 'gocoachapp-d882a',
    storageBucket: 'gocoachapp-d882a.appspot.com',
    iosBundleId: 'com.example.adminPanelGocoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF0FRAvZTI1yV-TNhhF9cCx37swU1YvU0',
    appId: '1:203559158951:web:13dde69c7b1aaca95d8782',
    messagingSenderId: '203559158951',
    projectId: 'gocoachapp-d882a',
    authDomain: 'gocoachapp-d882a.firebaseapp.com',
    storageBucket: 'gocoachapp-d882a.appspot.com',
    measurementId: 'G-MP35SN2C6B',
  );

}